using Application.DTOs.Maintenance;

namespace Application.Services.Interfaces;

public interface IMaintenancePlanService
{
    Task<IReadOnlyList<MaintenancePlanDto>> GetAllAsync(
        Guid tenantId,
        Guid? assetId = null,
        bool includeInactive = false,
        CancellationToken ct = default);

    Task<MaintenancePlanDto?> GetByIdAsync(Guid tenantId, Guid planId, CancellationToken ct = default);

    Task<IReadOnlyList<MaintenanceCalendarOccurrenceDto>> GetCalendarAsync(
        Guid tenantId,
        DateTime fromUtc,
        DateTime toUtc,
        Guid? assetId = null,
        CancellationToken ct = default);

    Task<MaintenancePlanDto> CreateAsync(Guid tenantId, CreateMaintenancePlanRequest request, CancellationToken ct = default);
    Task<MaintenancePlanDto> UpdateAsync(Guid tenantId, Guid planId, UpdateMaintenancePlanRequest request, CancellationToken ct = default);
    Task<MaintenancePlanDto> CompleteAsync(Guid tenantId, Guid planId, CompleteMaintenanceOccurrenceRequest request, CancellationToken ct = default);
    Task<MaintenanceAutomationSyncDto> SyncAutoGeneratedWorkOrdersAsync(Guid tenantId, Guid? assetId = null, CancellationToken ct = default);
}
