using Application.DTOs.Maintenance;
using Application.Services.Interfaces;
using FlowCraft.Domain.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FlowCraft.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public sealed class MaintenancePlansController : ControllerBase
{
    private readonly IMaintenancePlanService _service;
    private readonly ILogger<MaintenancePlansController> _logger;

    public MaintenancePlansController(
        IMaintenancePlanService service,
        ILogger<MaintenancePlansController> logger)
    {
        _service = service;
        _logger = logger;
    }

    [HttpGet]
    public async Task<ActionResult<IReadOnlyList<MaintenancePlanDto>>> GetAll(
        [FromQuery] Guid? assetId,
        [FromQuery] bool includeInactive,
        CancellationToken ct)
    {
        var tenantId = User.GetTenantId();
        var plans = await _service.GetAllAsync(tenantId, assetId, includeInactive, ct);
        return Ok(plans);
    }

    [HttpGet("calendar")]
    public async Task<ActionResult<IReadOnlyList<MaintenanceCalendarOccurrenceDto>>> GetCalendar(
        [FromQuery] DateTime fromUtc,
        [FromQuery] DateTime toUtc,
        [FromQuery] Guid? assetId,
        CancellationToken ct)
    {
        var tenantId = User.GetTenantId();

        try
        {
            var calendar = await _service.GetCalendarAsync(tenantId, fromUtc, toUtc, assetId, ct);
            return Ok(calendar);
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpGet("{id:guid}")]
    public async Task<ActionResult<MaintenancePlanDto>> GetById(Guid id, CancellationToken ct)
    {
        var tenantId = User.GetTenantId();
        var plan = await _service.GetByIdAsync(tenantId, id, ct);
        return plan is null ? NotFound() : Ok(plan);
    }

    [HttpPost]
    [Authorize(Roles = $"{Roles.Admin},{Roles.Manager},{Roles.Editor}")]
    public async Task<ActionResult<MaintenancePlanDto>> Create([FromBody] CreateMaintenancePlanRequest request, CancellationToken ct)
    {
        var tenantId = User.GetTenantId();

        try
        {
            var plan = await _service.CreateAsync(tenantId, request, ct);
            _logger.LogInformation("Maintenance plan created. tenantId={TenantId}, planId={PlanId}", tenantId, plan.Id);
            return CreatedAtAction(nameof(GetById), new { id = plan.Id }, plan);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpPut("{id:guid}")]
    [Authorize(Roles = $"{Roles.Admin},{Roles.Manager},{Roles.Editor}")]
    public async Task<ActionResult<MaintenancePlanDto>> Update(Guid id, [FromBody] UpdateMaintenancePlanRequest request, CancellationToken ct)
    {
        var tenantId = User.GetTenantId();

        try
        {
            var plan = await _service.UpdateAsync(tenantId, id, request, ct);
            _logger.LogInformation("Maintenance plan updated. tenantId={TenantId}, planId={PlanId}", tenantId, id);
            return Ok(plan);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpPost("{id:guid}/complete")]
    [Authorize(Roles = $"{Roles.Admin},{Roles.Manager},{Roles.Editor}")]
    public async Task<ActionResult<MaintenancePlanDto>> Complete(Guid id, [FromBody] CompleteMaintenanceOccurrenceRequest request, CancellationToken ct)
    {
        var tenantId = User.GetTenantId();

        try
        {
            var plan = await _service.CompleteAsync(tenantId, id, request, ct);
            _logger.LogInformation("Maintenance occurrence completed. tenantId={TenantId}, planId={PlanId}", tenantId, id);
            return Ok(plan);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpPost("sync-auto-work-orders")]
    [Authorize(Roles = $"{Roles.Admin},{Roles.Manager},{Roles.Editor}")]
    public async Task<ActionResult<MaintenanceAutomationSyncDto>> SyncAutoWorkOrders(
        [FromQuery] Guid? assetId,
        CancellationToken ct)
    {
        var tenantId = User.GetTenantId();
        var result = await _service.SyncAutoGeneratedWorkOrdersAsync(tenantId, assetId, ct);
        return Ok(result);
    }
}
